# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
- develop
- feature/*
- bugfix*

pool:
  name: Azure Pipelines
  demands: docker



variables:
  repository: 'walmartpayment'
  
stages:
- stage: 'DockerBuild'
  jobs:
  - job: 'DockerBuild'
    steps:
   
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerAcr'
        repository: '$(repository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 
         latest
         $(Build.BuildNumber)